"""SHRED on ME4OH full-field OFAM3 SST data

Investigating how changing number of static sensors changes the resulting metrics.

Note: Assumptions as of 30/06/26
- OFAM3 data is stored for Thursdays across the 1979-2014 time period.
- Pending confirmation from the ME4OH team, I have assumed that the data is the full-field SST values generated by the simulator model (OFAM3) averaged across a calendar week
"""
import argparse
import json

# Third-party imports
import numpy as np
import torch
from sklearn.preprocessing import MinMaxScaler
from skimage.metrics import structural_similarity as SSI
from sklearn.metrics import mean_squared_error as MSE
from sklearn.metrics import mean_absolute_error as MAE
from sklearn.metrics import r2_score
from tqdm import tqdm

# Local imports
import models  # https://github.com/Jan-Williams/pyshred/blob/main/models.py 
from Data.preprocess_sst_ofam3_shred import create_shred_sequences, load_files, split_ordered_data
from helper_functions.evaluation import mask_array_by_lat_long

np.random.seed(42)


def train_models():
    """Load data and train models with varying numbers of static sensors placed randomly"""
    # Load and reformat data
    data, dates, lats, longs = load_files()

    print("Preprocessing data...")
    train_data, val_data, test_data, test_dates = split_ordered_data(data, dates)

    # Normalise data
    sc = MinMaxScaler()
    sc = sc.fit(train_data)  # Computes min and max from training data only (prevent data leakage)
    train_transformed = sc.transform(train_data)  
    val_transformed = sc.transform(val_data)
    test_transformed = sc.transform(test_data)

    num_points = 60
    quantities = range(1, len(lats), round(len(lats)/num_points))
    lags = 52

    for num_sensors in tqdm(quantities, "Training models"):
        print("Number of sensors: ", num_sensors)
        # Get sensor locations
        sensor_locations = np.random.choice(data.shape[1], size=num_sensors, replace=False)
        # print(f"Sensor location indexes will be: {sensor_locations}")

        # Build sequences
        train_dataset = create_shred_sequences(train_transformed, sensor_locations, lags=lags)
        val_dataset = create_shred_sequences(val_transformed, sensor_locations, lags=lags)
        test_dataset = create_shred_sequences(test_transformed, sensor_locations, lags=lags)

        # Train model
        print("Training model...")
        device = 'cuda' if torch.cuda.is_available() else 'cpu'
        shred = models.SHRED(num_sensors, len(lats), hidden_size=64, hidden_layers=2, l1=350, l2=400, dropout=0.1).to(device)
        _ = models.fit(shred, train_dataset, val_dataset, batch_size=64, num_epochs=1000, lr=1e-3, patience=5)

        # Test model
        print("Testing ...")
        test_recons = sc.inverse_transform(shred(test_dataset.X).detach().cpu().numpy())
        test_ground_truth = sc.inverse_transform(test_dataset.Y.detach().cpu().numpy())
        print('Test Reconstruction Error: ')
        print(np.linalg.norm(test_recons - test_ground_truth) / np.linalg.norm(test_ground_truth))

        # Save reconstruction
        np.save(f"Reconstructions/change_num_sensors/recons_n{num_sensors}_l{lags}", test_recons)
        np.save(f"Reconstructions/change_num_sensors/truth_n{num_sensors}_l{lags}", test_ground_truth)


def evaluate_reconstructions():
    """Load data and train models with varying numbers of static sensors placed randomly"""
    # Load data
    _, _, lats, longs = load_files()

    num_points = 60
    quantities = range(1, len(lats), round(len(lats)/num_points))
    lags = 52

    results = {}
    for num_sensors in tqdm(quantities, "Evaluating reconstructions"):
        # Load data
        try:
            test_recons = np.load(f"Reconstructions/change_num_sensors/recons_n{num_sensors}_l{lags}.npy")
            test_ground_truth = np.load(f"Reconstructions/change_num_sensors/truth_n{num_sensors}_l{lags}.npy")
        except FileNotFoundError:
            break

        # Metrics for NA basin
        ssi = np.mean([SSI(test_ground_truth[i], test_recons[i], 
                   data_range=(max(test_recons[i].max(), test_ground_truth[i].max()) - min(test_recons[i].min(), test_ground_truth[i].min())))
                   for i in range(len(test_recons))])
        difference = test_recons - test_ground_truth
        avg_difference = [np.mean(d) for d in difference]
        avg_all_time_difference = float(np.mean(avg_difference))

        NA_results = {
            "RMSE": np.sqrt(MSE(y_pred=test_recons, y_true=test_ground_truth)),
            "MAE": MAE(y_pred=test_recons, y_true=test_ground_truth),
            "R2": r2_score(y_pred=test_recons, y_true=test_ground_truth),
            "Average SSI": ssi,
            "Average all time diff": avg_all_time_difference
        }

        # Metrics for GS region
        GS_data = mask_array_by_lat_long(difference, lats, longs)
        GS_test_data = mask_array_by_lat_long(test_recons, lats, longs)
        GS_truth_data = mask_array_by_lat_long(test_ground_truth, lats, longs)
        GS_data = [d[~np.isnan(d)] for d in GS_data]
        GS_test_data = [d[~np.isnan(d)] for d in GS_test_data]
        GS_truth_data = [d[~np.isnan(d)] for d in GS_truth_data]

        ssi = np.mean([SSI(GS_truth_data[i], GS_test_data[i],
                           data_range=test_recons[i].max() -  test_recons[i].min())
                       for i in range(len(test_recons))])
        gs_avg_difference = [np.mean(d) for d in GS_data]
        gs_avg_all_time_difference = float(np.mean(gs_avg_difference))

        GS_results = {
            "RMSE": np.sqrt(MSE(y_pred=GS_test_data, y_true=GS_truth_data)),
            "MAE": MAE(y_pred=GS_test_data, y_true=GS_truth_data),
            "R2": r2_score(y_pred=GS_test_data, y_true=GS_truth_data),
            "Average SSI": ssi,
            "Average all time diff": gs_avg_all_time_difference
        }

        results[num_sensors] = {"NA": NA_results, "GS": GS_results}

    with open("Reconstructions/change_num_sensors/eval_metric_results.json", 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=4)


parser = argparse.ArgumentParser()
parser.add_argument("-t", "--train", action="store_true", help="Train models if this flag is used")
parser.add_argument("-e", "--eval", action="store_true", help="Evaluate reconstructions if this flag is used")
args = parser.parse_args()

if args.train:
    print("Mode: Train models")
    train_models()
if args.eval:
    print("Mode: Evaluate reconstructions")
    evaluate_reconstructions()