"""SHRED on ME4OH full-field OFAM3 SST data

Investigating how changing number of static sensors changes the resulting metrics.

Note: Assumptions as of 30/06/26
- OFAM3 data is stored for Thursdays across the 1979-2014 time period.
- Pending confirmation from the ME4OH team, I have assumed that the data is the full-field SST values generated by the simulator model (OFAM3) averaged across a calendar week
"""
# Third-party imports
import numpy as np
import torch
from sklearn.preprocessing import MinMaxScaler

# Local imports
import models  # https://github.com/Jan-Williams/pyshred/blob/main/models.py 
from Data.preprocess_sst_ofam3_shred import create_shred_sequences, load_files, split_ordered_data

np.random.seed(42)

if __name__ == "__main__":
    # Load and reformat data
    data, dates, lats, longs = load_files()

    num_points = 30
    quantities = range(1, len(lats), len(lats)/60)
    lags = 52

    for num_sensors in quantities:
        print("Preprocessing data...")
        train_data, val_data, test_data, test_dates = split_ordered_data(data, dates)

        # Normalise data
        sc = MinMaxScaler()
        sc = sc.fit(train_data)  # Computes min and max from training data only (prevent data leakage)
        train_transformed = sc.transform(train_data)  
        val_transformed = sc.transform(val_data)
        test_transformed = sc.transform(test_data)

        # Build sequences
        sensor_locations = np.random.choice(data.shape[1], size=num_sensors, replace=False)
        sensor_coords=(longs[sensor_locations], lats[sensor_locations])
        # print(f"Sensor location indexes will be: {sensor_locations}")

        # Build sequences
        train_dataset = create_shred_sequences(train_transformed, sensor_locations, lags=lags)
        val_dataset = create_shred_sequences(val_transformed, sensor_locations, lags=lags)
        test_dataset = create_shred_sequences(test_transformed, sensor_locations, lags=lags)

        # Get dates corresponding to the predictions made by the model
        test_lag_dates = test_dates[np.array(range(len(test_dates)-lags)) + lags - 1]

        # Train model
        device = 'cuda' if torch.cuda.is_available() else 'cpu'
        shred = models.SHRED(num_sensors, len(lats), hidden_size=64, hidden_layers=2, l1=350, l2=400, dropout=0.1).to(device)
        validation_errors = models.fit(shred, train_dataset, val_dataset, batch_size=64, num_epochs=1000, lr=1e-3, verbose=True, patience=5)

        # Test model
        test_recons = sc.inverse_transform(shred(test_dataset.X).detach().cpu().numpy())
        test_ground_truth = sc.inverse_transform(test_dataset.Y.detach().cpu().numpy())
        print('Test Reconstruction Error: ')
        print(np.linalg.norm(test_recons - test_ground_truth) / np.linalg.norm(test_ground_truth))

        # Save reconstruction
        np.save(f"Reconstructions/change_num_sensors/recons_n{num_sensors}_l{lags}", test_recons)
        np.save(f"Reconstructions/change_num_sensors/truth_n{num_sensors}_l{lags}", test_ground_truth)
